runtime: python27
api_version: 1
threadsafe: true
handlers:
  - url: /
    static_files: dist/github-test/index.html
    upload: dist/github-test/index.html
  - url: /
    static_dir: dist/github-test/
    
# skip_files can also be transfered into an .gcloudignore file
skip_files:
  - e2e/
  - node_modules/
  - src/
  - coverage
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE